#model
transformer_model:
  model: "cointegrated/rubert-tiny"
  path_to_state_dict: false
  device: cpu
  dropout: 0.2
  tiny_bert: true
  learning_rate: 1e-6
  batch_size: 8
  shuffle: true
  maxlen: 512

# data
data:
  train_data_path: gvk_dnie_one_list.xlsx
  test_data_path:
  text_column: Комментарий
  target_column: target
  random_state: 42
  test_size: 0.9

# training
training:
  num_epocs: 1
  average_f1: macro
  output_dir: results/